### PR TITLE
328 voice command repeat step

### PR DESCRIPTION
**Pull request by KagisoLegodi**

### CODE REVIEW

**Review by NeoPhetoane — CHANGES_REQUESTED** [review]
Successfully repeats steps, pauses but cannot resume. I get the error "Cannot resume as the speech synthesis is not paused."

**Review by IkanyengAdams — DISMISSED** [review]
all checks passed successfully.

**Review by NeoPhetoane — APPROVED** [review]
Successfully stops, pauses, removes and repeats steps. Toggle theme classes have been removed, will be solved during merge conflicts.

**Review by NeoPhetoane — APPROVED** [review]
All tests passed

**Review by IkanyengAdams — APPROVED** [review]
all checks passed successfully

**Pull request merged**
