### PR TITLE
Updated login page to redirect to intended page after login, and modi…

### LINKED ISSUE #194: Redirect to Previously Attempted Page After Login
As a user trying to access a protected page, I want to be redirected to my intended page after logging in, so that I can continue from where I left off.

### PR DESCRIPTION
**Pull request by Mokawane**
…fied middleware to redirect to login page with original requested path as query parameter when no token is found or token verification fails.

N.B
I protected the recipes page for testing purposes only, as no routes were protected.

closes #194

### CODE REVIEW

**Review by OmphileMorwane — CHANGES_REQUESTED** [review]
No redirection after log in

**Review by NeoPhetoane — CHANGES_REQUESTED** [review]
Protected routes take you to log-in page successfully, but does not redirect to previous page after.

**Review by OmphileMorwane — CHANGES_REQUESTED** [review]
Code has bugs, it is not redirecting to the recipe page as instructed.

**Review by OmphileMorwane — CHANGES_REQUESTED** [review]
Log in not redirecting to page

**Pull request closed without merging**
