### PR TITLE
Add dynamic metadata for recipe detail page#124

### PR DESCRIPTION
**Pull request by OmphileMorwane**
js Docs not reflecting on the new branch. Kindly fetch and pull to see updates. Regards

### CODE REVIEW

**Review by KagisoLegodi — APPROVED** [review]
Js doc visible

**Review by KagisoLegodi — CHANGES_REQUESTED** [review]
There are merge conflicts in your code

**Review by IkanyengAdams — DISMISSED** [review]
this pull request, added dynamic metadata.

**Review by KagisoLegodi — APPROVED** [review]
Dynamic Meta Data succefully linked

**Pull request merged**
