### PR TITLE
Refactor login route, layout, and middleware; update token generation…

### PR DESCRIPTION
**Pull request by Mokawane**
…, cookie settings, and authentication flow

### CODE REVIEW

**Review by OmphileMorwane — APPROVED** [review]
All test passed, toggle visible on the console.

**Review by NeoPhetoane — CHANGES_REQUESTED** [review]
How do i test it? Can you provide tests with the pull request.
There is another interfering loading state in the layout

**Review by HloleloRampete — APPROVED** [review]
The code passes all tests

**Review by OmphileMorwane — CHANGES_REQUESTED** [review]
code not tested

**Pull request closed without merging**
