### PR TITLE
feat: update fetch functions for API calls

### PR DESCRIPTION
**Pull request by KagisoLegodi**
- Modified fetchRecipes to construct the URL for fetching paginated recipes from the '/api/recipes' endpoint using query parameters for pagination.
- Updated fetchProductById to correctly fetch a single product by its ID from the '/api/recipes/[id]' endpoint using the BASE_URL from environment variables.

### CODE REVIEW

**Review by tsaimogono — DISMISSED** [review]
fetches a paginated list of recipes from the /api/recipes endpoint using query parameters for pagination.correctly..The URL includes page and limit as query parameters to fetch specific pages and control the number of items per page.The URL includes the id parameter to fetch a specific recipe. This ensures the request is made to the correct endpoint for that particular recipe.

**Review by ElzabeEls — CHANGES_REQUESTED** [review]
very close. although /api/recipes?page=${page}&limit=${limit} should also become ${process.env.BASE_URL}/api/recipes?page=${page}&limit=${limit}

**Review by OmphileMorwane — DISMISSED** [review]
-Correct Use of Parameters: Each function uses parameters (page, limit, id) correctly, which enables reuse and flexibility.
-Error Handling: Both functions implement error handling, making the code robust against failed API calls.
-API Response Handling: The code checks if the response is successful (response.ok), ensuring that only valid data is returned.
-Environment Variable Usage: Using process.env.BASE_URL for -URLs would ensure the code is deployable across different environments (e.g., development, testing, production).

**Comment by ElzabeEls** [comment]
@OmphileMorwane @tsaimogono did you run the code before what looks like asking ChatGPT to generate a comment for you? This code would fail. Please run the code locally before approving changes. You would have allowed te main to get broken if I did not review this code as well.

**Comment by ElzabeEls** [comment]
@IkanyengAdams, please see that everyone who approves a request checks out and runs the code locally before approving a merge request. Remember that GitHub allows one to trace who approved what code to merge. Thank you!

**Review by ElzabeEls — APPROVED** [review]

**Pull request merged**
