### PR TITLE
clearing advanced filtering completed with additional css implemented

### PR DESCRIPTION
**Pull request by Moosa-24**
Advanced Filtering:
Implemented clearing of all _current_ filters from advanced filtering, 
I also added some CSS to the component to make it look somewhat decent.

header:
I removed the extra search bar, and switched over the recipes/favorites links.

Screenshot (525)
Screenshot (526)

### CODE REVIEW

**Review by KagisoLegodi — APPROVED** [review]
All tests passed the styling is more appealing

**Review by KagisoLegodi — CHANGES_REQUESTED** [review]
please verify this 
Screenshot 2024-11-12 091438

**Review by KagisoLegodi — APPROVED** [review]
all changes complete

**Review by Mokawane — APPROVED** [review]
It works perfectly.

**Pull request merged**
