### PR TITLE
Login route for email and password #202

### PR DESCRIPTION
**Pull request by NeoPhetoane**

### CODE REVIEW

**Review by KagisoLegodi — APPROVED** [review]
all tests passed

**Review by Mokawane — APPROVED** [review]
It works right for me.

I think you could reduce the token expiration time.

Thank you.

**Review by Mokawane — APPROVED** [review]
It works perfectly from my side.

I would advise using a shorter token expiry.

**Review by IkanyengAdams — APPROVED** [review]
This pull request, Login route for email and password all checks passed successfully

**Pull request merged**
